/**
 * Serves the repository's example scenes and robot assets to the studio under `/repo/`, and
 * lists the examples as the virtual module `virtual:etendue-examples`.
 *
 * - dev: a middleware reads `examples/**` and `assets/robots/**` from the checkout;
 * - build: the same files are emitted into `dist/repo/`.
 *
 * Nothing else of the repository is exposed. Robot meshes (`assets/robots/*\/meshes/`) are
 * generated by `tools/robot-assets/build.py`; without them robots are drawn as link axes.
 */

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { extname, join, relative, resolve, sep } from "node:path";

import type { Plugin } from "vite";

const ROOT = resolve(import.meta.dirname, "../../..");
const SERVED = ["examples", "assets/robots"];
const VIRTUAL = "virtual:etendue-examples";
const TYPES: Record<string, string> = {
  ".json": "application/json",
  ".urdf": "application/xml",
  ".glb": "model/gltf-binary",
};

function* walk(dir: string): Generator<string> {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) yield* walk(path);
    else yield path;
  }
}

/** Every example: a directory of `examples/` with a `scene.json`. */
function examples() {
  return readdirSync(join(ROOT, "examples"))
    .filter((id) => existsSync(join(ROOT, "examples", id, "scene.json")))
    .sort()
    .map((id) => {
      const scene = JSON.parse(readFileSync(join(ROOT, "examples", id, "scene.json"), "utf8")) as {
        description?: string;
      };
      const scenario = existsSync(join(ROOT, "examples", id, "scenario.json"))
        ? `examples/${id}/scenario.json`
        : null;
      return { id, description: scene.description ?? "", scene: `examples/${id}/scene.json`, scenario };
    });
}

export function etendueRepo(): Plugin {
  return {
    name: "etendue-repo",
    resolveId(id) {
      return id === VIRTUAL ? `\0${VIRTUAL}` : null;
    },
    load(id) {
      return id === `\0${VIRTUAL}` ? `export default ${JSON.stringify(examples())};` : null;
    },
    configureServer(server) {
      server.middlewares.use("/repo", (req, res, next) => {
        const path = decodeURIComponent((req.url ?? "/").split("?")[0]!).replace(/^\/+/, "");
        const file = resolve(ROOT, path);
        const allowed = SERVED.some((dir) => file.startsWith(join(ROOT, dir) + sep));
        if (!allowed || !existsSync(file) || !statSync(file).isFile()) return next();
        res.setHeader("Content-Type", TYPES[extname(file)] ?? "application/octet-stream");
        res.end(readFileSync(file));
      });
    },
    generateBundle() {
      for (const dir of SERVED) {
        for (const file of walk(join(ROOT, dir))) {
          this.emitFile({
            type: "asset",
            fileName: `repo/${relative(ROOT, file).split(sep).join("/")}`,
            source: readFileSync(file),
          });
        }
      }
    },
  };
}
